#pragma once

#define HAL_BOARD_NAME "SPRESENSE-M1"
#define HAL_CPU_CLASS HAL_CPU_CLASS_150
#define HAL_MEM_CLASS HAL_MEM_CLASS_1000
#define CONFIG_HAL_BOARD_SUBTYPE HAL_BOARD_SUBTYPE_NONE

#define HAL_STORAGE_SIZE 16384
#define HAL_STORAGE_SIZE_AVAILABLE HAL_STORAGE_SIZE

// No Copter flash budget is claimed before the first Sony linker map.
#define HAL_PROGRAM_SIZE_LIMIT_KB 0

#define HAL_OS_POSIX_IO 1
#define HAL_OS_SOCKETS 0
#define HAL_NUM_CAN_IFACES 0
#define HAL_INS_DEFAULT HAL_INS_NONE

#define HAL_HAVE_BOARD_VOLTAGE 0
#define HAL_HAVE_SERVO_VOLTAGE 0
#define HAL_HAVE_SAFETY_SWITCH 0

#define AP_SCRIPTING_ENABLED 0
#define AP_NETWORKING_ENABLED 0
