############################################################################
# Tools/spresense/Makefile
#
# SPDX-License-Identifier: GPL-3.0-or-later
############################################################################

MENUDESC = "ArduPilot Spresense bring-up"

include $(SDKDIR)/tools/Sdk.mk
